/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
static yyconst short int yy_accept[448] =
    {   0,
        0,    0,   83,   81,   80,   79,   81,   81,   81,   72,
       81,   74,   81,   81,   81,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   81,   78,   78,   66,   80,    0,   76,   75,
        1,    2,    0,    0,   71,   73,   74,   68,   70,   67,
       51,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   69,   78,   28,    1,    0,   77,   73,    0,

       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,    0,    0,    0,   73,   78,   78,   78,   78,   78,
       78,   58,    8,   78,   78,   78,   78,   78,   78,   78,
       78,    6,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   38,   78,

       78,   78,   78,   78,   78,   78,   78,   32,    0,    0,
       78,   78,   78,   78,   78,   78,   78,   78,   25,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   52,   78,   78,   78,   78,   78,   78,
       78,   78,   78,    5,   33,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
        0,    0,   78,   78,   78,   78,   78,   47,   78,   39,
       78,   78,   78,   78,   78,   78,   78,   78,   59,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       60,   78,   78,   78,   78,   78,   30,   20,   78,   78,

       78,   78,   14,   78,   78,   78,   78,   78,   10,   78,
       78,    0,    0,   78,   35,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   65,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   56,   57,   78,   78,   78,   78,
       78,   31,   78,   78,   78,   37,   78,   78,   78,   46,
       40,   78,   78,   78,    0,    0,   78,   78,   78,   78,
       78,    7,   17,   78,   78,   78,   78,   78,   61,   23,
       49,   78,   78,   78,   78,   78,   78,   53,   15,   78,
       78,   16,   78,   78,   78,   50,   42,   78,   78,   78,
        0,    4,   78,   29,   18,   78,   78,   78,   24,   78,

       62,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       34,   36,   19,   22,   44,   48,    3,   78,   78,   26,
       78,   64,   78,   78,   43,   41,   78,   11,   12,   78,
        9,   54,   55,   78,   78,   78,   27,   78,   78,   63,
       78,   78,   45,   78,   13,   21,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    6,    1,
        1,    1,    7,    8,    9,   10,    1,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,    1,   13,
       14,   15,    1,    1,   16,   17,   18,   19,   20,   21,
       22,   22,   23,   22,   22,   24,   25,   26,   27,   28,
       22,   29,   30,   31,   32,   22,   33,   22,   22,   22,
       34,    1,   35,    1,   22,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   45,   22,   46,   47,   48,
       49,   50,   22,   51,   52,   53,   54,   55,   56,   57,
       58,   59,    1,   60,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[61] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        4,    1,    1,    1,    1,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    1,    1,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1
    } ;

static yyconst short int yy_base[452] =
    {   0,
        0,    0,  489,  490,  486,  490,   58,   58,    0,  490,
      477,   56,   49,  474,  473,   31,   29,   31,   30,  440,
       36,    0,   42,  434,   39,   48,   54,   44,   52,   60,
       63,  446,  469,  423,  431,  490,  476,  105,  490,  490,
        0,  490,  426,  470,  490,   95,  101,  490,  490,  490,
      490,    0,   64,  428,  421,  427,  423,  418,  424,   24,
      431,   78,  416,  414,  417,  419,  424,  419,  410,  443,
      424,   72,   71,  417,   90,  412,  405,  414,  399,  405,
       84,   77,  402,  416,   80,  411,  402,  401,  397,  395,
      396,  394,  490,  400,    0,    0,   84,  490,  121,  133,

      388,  423,  397,  400,  390,  388,  394,  390,  382,  390,
      387,  106,  394,  391,  387,  373,  382,  387,  377,  372,
      373,  384,  373,  383,  390,   97,  394,  382,  381,  388,
      369,  374,  377,  372,  358,  361,  355,  355,  359,  366,
      359,  364,  363,  364,  365,  358,  352,  346,  357,  357,
      342,  342,  340,  381,  380,  350,  340,  336,  336,  330,
      333,    0,    0,  340,  335,  342,  341,  332,  336,  126,
      338,    0,  328,  343,  325,  323,  329,  328,  320,  327,
      333,  332,  316,  330,  312,  317,  327,  331,  310,  312,
      308,  309,  306,  310,  337,  315,  313,  312,    0,  321,

      306,  299,  308,  303,  292,  329,  328,    0,  305,  293,
      315,  288,  287,  290,  311,  278,  287,  294,    0,  280,
      283,  295,  286,  103,  283,  277,  271,  290,  289,  270,
      270,  274,  294,    0,  279,  278,  291,  264,  276,  265,
      261,  269,  257,    0,    0,  273,  271,  256,  272,  118,
      259,  267,  267,  257,  251,  254,  253,  260,  253,  252,
      246,  258,  246,  254,  249,  256,  242,    0,  236,    0,
      249,  236,  236,  231,  237,  245,  237,  228,    0,  249,
      229,  226,  231,  233,  234,  224,  234,  233,  221,  233,
        0,  224,  226,  216,  227,  217,    0,    0,  211,  215,

      213,  218,    0,  225,  220,  219,  205,  221,    0,  212,
      209,  210,  204,  201,    0,  202,  197,  198,  199,  195,
      109,  204,  201,  190,    0,  190,  190,  191,  201,  196,
      198,  199,  217,  193,    0,    0,  192,  190,  192,  182,
      178,    0,  183,  176,  171,    0,  178,  177,  176,    0,
        0,  170,  186,  172,  183,  173,  171,  169,  176,  168,
      160,    0,    0,  161,  172,  172,  158,  165,    0,    0,
        0,  164,  159,  170,  156,  168,  167,    0,    0,  156,
      147,    0,  160,  151,  156,    0,    0,  157,  144,  157,
      154,  490,  157,    0,    0,  156,  139,  166,    0,  149,

        0,  138,  149,  133,  139,  132,  135,  134,  132,  140,
        0,    0,    0,    0,    0,    0,  490,  133,  132,    0,
      133,    0,  130,  157,    0,    0,  134,    0,    0,  129,
        0,    0,    0,  116,  109,  124,    0,  115,  105,    0,
      104,  117,    0,   94,    0,    0,  490,  161,  165,   92,
      169
    } ;

static yyconst short int yy_def[452] =
    {   0,
      447,    1,  447,  447,  447,  447,  448,  447,  449,  447,
      447,  447,  447,  447,  447,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  447,  450,  450,  447,  447,  448,  447,  447,
      451,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  447,  450,  450,  451,  447,  447,  447,  447,

      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  447,  447,  447,  447,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,

      450,  450,  450,  450,  450,  450,  450,  450,  447,  447,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      447,  447,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,

      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  447,  447,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  447,  447,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      447,  447,  450,  450,  450,  450,  450,  450,  450,  450,

      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  447,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,    0,  447,  447,  447,
      447
    } ;

static yyconst short int yy_nxt[551] =
    {   0,
        4,    5,    6,    7,    8,    9,    4,   10,    4,   11,
       12,   13,   14,   15,    4,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   22,   32,   33,    4,   22,   22,   22,   22,   34,
       22,   22,   22,   35,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   36,
       39,   40,   41,   48,   42,   46,   47,   53,   56,   54,
       59,  109,   57,   62,   72,  110,   55,   58,   63,   60,
       68,   65,   73,   49,   66,   43,   67,   74,   61,   69,
       77,   81,   79,   70,   80,   52,   75,   83,   88,   84,

       82,   76,   89,   85,   78,   99,   90,   39,   40,   86,
       46,   47,  101,  112,  100,  102,  123,   87,  126,  129,
       91,  136,  127,  152,  124,  138,  182,  142,  125,  113,
      139,   99,  153,  446,  100,  137,  300,  130,  143,  154,
      100,  154,  167,  155,  223,  183,  275,  168,  363,  301,
      224,  276,  364,  225,  445,  444,  277,  443,  442,  441,
      100,   38,   38,   38,   38,   44,  440,  439,   44,   96,
      438,   96,   96,  437,  436,  435,  434,  433,  432,  431,
      430,  429,  428,  427,  426,  425,  424,  423,  422,  421,
      420,  419,  418,  417,  416,  415,  414,  413,  412,  411,

      410,  409,  408,  407,  406,  405,  404,  403,  402,  401,
      400,  399,  398,  397,  396,  395,  394,  393,  392,  391,
      390,  389,  388,  387,  386,  385,  384,  383,  382,  381,
      380,  379,  378,  377,  376,  375,  374,  373,  372,  371,
      370,  369,  368,  367,  366,  365,  362,  361,  360,  359,
      358,  357,  356,  355,  354,  353,  352,  351,  350,  349,
      348,  347,  346,  345,  344,  343,  342,  341,  340,  339,
      338,  337,  336,  335,  334,  333,  332,  331,  330,  329,
      328,  327,  326,  325,  324,  323,  322,  321,  320,  319,
      318,  317,  316,  315,  314,  313,  312,  311,  310,  309,

      308,  307,  306,  305,  304,  303,  302,  299,  298,  297,
      296,  295,  294,  293,  292,  291,  290,  289,  288,  287,
      286,  285,  284,  283,  282,  281,  280,  279,  278,  274,
      273,  272,  271,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  261,  260,  259,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  235,  234,
      233,  232,  231,  230,  229,  228,  227,  226,  222,  221,
      220,  219,  218,  217,  216,  215,  214,  213,  212,  211,
      155,  155,  210,  209,  208,  207,  206,  205,  204,  203,

      202,  201,  200,  199,  198,  197,  196,  195,  194,  193,
      192,  191,  190,  189,  188,  187,  186,  185,  184,  181,
      180,  179,  178,  177,  176,  175,  174,  173,  172,  171,
      170,  169,  166,  165,  164,  163,  162,  161,  160,  159,
      158,  157,  156,  151,  150,  149,  148,  147,  146,  145,
      144,  141,  140,  135,  134,  133,  132,  131,  128,  122,
      121,  120,  119,  118,  117,  116,  115,  114,  111,  108,
      107,  106,  105,  104,  103,   98,   97,   37,   95,   94,
       93,   92,   71,   64,   51,   50,   45,   37,  447,    3,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,

      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447
    } ;

static yyconst short int yy_chk[551] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        7,    7,    8,   13,    8,   12,   12,   16,   17,   16,
       18,   60,   17,   19,   25,   60,   16,   17,   19,   18,
       23,   21,   25,   13,   21,    8,   21,   26,   18,   23,
       27,   29,   28,   23,   28,  450,   26,   30,   31,   30,

       29,   26,   31,   30,   27,   46,   31,   38,   38,   30,
       47,   47,   53,   62,   46,   53,   72,   30,   73,   75,
       31,   81,   73,   97,   72,   82,  126,   85,   72,   62,
       82,   99,   97,  444,   46,   81,  250,   75,   85,  100,
       99,  100,  112,  100,  170,  126,  224,  112,  321,  250,
      170,  224,  321,  170,  442,  441,  224,  439,  438,  436,
       99,  448,  448,  448,  448,  449,  435,  434,  449,  451,
      430,  451,  451,  427,  424,  423,  421,  419,  418,  410,
      409,  408,  407,  406,  405,  404,  403,  402,  400,  398,
      397,  396,  393,  391,  390,  389,  388,  385,  384,  383,

      381,  380,  377,  376,  375,  374,  373,  372,  368,  367,
      366,  365,  364,  361,  360,  359,  358,  357,  356,  355,
      354,  353,  352,  349,  348,  347,  345,  344,  343,  341,
      340,  339,  338,  337,  334,  333,  332,  331,  330,  329,
      328,  327,  326,  324,  323,  322,  320,  319,  318,  317,
      316,  314,  313,  312,  311,  310,  308,  307,  306,  305,
      304,  302,  301,  300,  299,  296,  295,  294,  293,  292,
      290,  289,  288,  287,  286,  285,  284,  283,  282,  281,
      280,  278,  277,  276,  275,  274,  273,  272,  271,  269,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  258,

      257,  256,  255,  254,  253,  252,  251,  249,  248,  247,
      246,  243,  242,  241,  240,  239,  238,  237,  236,  235,
      233,  232,  231,  230,  229,  228,  227,  226,  225,  223,
      222,  221,  220,  218,  217,  216,  215,  214,  213,  212,
      211,  210,  209,  207,  206,  205,  204,  203,  202,  201,
      200,  198,  197,  196,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  184,  183,  182,  181,  180,
      179,  178,  177,  176,  175,  174,  173,  171,  169,  168,
      167,  166,  165,  164,  161,  160,  159,  158,  157,  156,
      155,  154,  153,  152,  151,  150,  149,  148,  147,  146,

      145,  144,  143,  142,  141,  140,  139,  138,  137,  136,
      135,  134,  133,  132,  131,  130,  129,  128,  127,  125,
      124,  123,  122,  121,  120,  119,  118,  117,  116,  115,
      114,  113,  111,  110,  109,  108,  107,  106,  105,  104,
      103,  102,  101,   94,   92,   91,   90,   89,   88,   87,
       86,   84,   83,   80,   79,   78,   77,   76,   74,   71,
       70,   69,   68,   67,   66,   65,   64,   63,   61,   59,
       58,   57,   56,   55,   54,   44,   43,   37,   35,   34,
       33,   32,   24,   20,   15,   14,   11,    5,    3,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,

      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "medlang.l"
#define INITIAL 0
#line 2 "medlang.l"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ast.h"
#include "medlang.tab.h"    /* generated by bison -d medlang.y */


int lineno = 1;

/* Forward declarations */
void yyerror(const char *s);
/* -- Named patterns ------------------------------------------------------------*/
#line 649 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 29 "medlang.l"


#line 803 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 448 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 490 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 31 "medlang.l"
{ /* skip */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 33 "medlang.l"
{
                        int c, prev = 0;
                        while (1) {
                            c = input();
                            if (c == EOF) {
                                fprintf(stderr,
                                    "[MedLang Error] Line %d: unterminated multi-line comment\n",
                                    lineno);
                                break;
                            }
                            if (c == '\n') lineno++;
                            if (prev == '+' && c == '#') {
                                break;
                            }
                            prev = c;
                        }
                    }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 51 "medlang.l"
{ return PRESCRIBE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 52 "medlang.l"
{ return DEFINE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 54 "medlang.l"
{ return ORGAN; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 55 "medlang.l"
{ return FLOW; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 56 "medlang.l"
{ return DIABETES; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 57 "medlang.l"
{ return CELL; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 58 "medlang.l"
{ return NULLTISSUE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 59 "medlang.l"
{ return TISSUE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 60 "medlang.l"
{ return MAJORORGAN; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 61 "medlang.l"
{ return MINORORGAN; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 62 "medlang.l"
{ return NONPATHOLOGIC; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 64 "medlang.l"
{ return SEALED; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 65 "medlang.l"
{ return NOSAMPLE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 66 "medlang.l"
{ return PROTOCOL; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 68 "medlang.l"
{ return DIAGNOSE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 69 "medlang.l"
{ return ALTERNATE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 70 "medlang.l"
{ return SCREENING; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 71 "medlang.l"
{ return RESULT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 72 "medlang.l"
{ return IDIOPATHICCASE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 73 "medlang.l"
{ return TERMINATE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 74 "medlang.l"
{ return FOLLOWUP; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 75 "medlang.l"
{ return DISCHARGE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 77 "medlang.l"
{ return CYCLE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 78 "medlang.l"
{ return CONTINUOUS; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 79 "medlang.l"
{ return LOADINGDOSE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 80 "medlang.l"
{ return IN_KW; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 82 "medlang.l"
{ return ADMISSION; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 84 "medlang.l"
{ return RECORD_KW; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 85 "medlang.l"
{ return OBSERVE_KW; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 86 "medlang.l"
{ return EXIT_KW; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 88 "medlang.l"
{ return POWER_FN; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 89 "medlang.l"
{ return ROOTCAUSE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 90 "medlang.l"
{ return ABSDOSE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 91 "medlang.l"
{ return ROUNDDOWN; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 92 "medlang.l"
{ return ROUNDUP; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 93 "medlang.l"
{ return SINE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 94 "medlang.l"
{ return COSINE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 95 "medlang.l"
{ return TANGENT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 96 "medlang.l"
{ return ISCRITICAL; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 98 "medlang.l"
{ return RECORD_STRUCT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 99 "medlang.l"
{ return INSTRUMENT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 100 "medlang.l"
{ return TYPEALIAS; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 101 "medlang.l"
{ return DIAGNOSISLIST; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 103 "medlang.l"
{ return SYNAPSE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 104 "medlang.l"
{ return BIOPSY; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 105 "medlang.l"
{ return WARDALLOC; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 106 "medlang.l"
{ return FREEWARD; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 107 "medlang.l"
{ return SIZESCAN; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 109 "medlang.l"
{ return ASSIGN; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 110 "medlang.l"
{ return EQ; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 111 "medlang.l"
{ return NEQ; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 112 "medlang.l"
{ return GT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 113 "medlang.l"
{ return LT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 114 "medlang.l"
{ return GEQ; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 115 "medlang.l"
{ return LEQ; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 116 "medlang.l"
{ return AND; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 117 "medlang.l"
{ return OR; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 118 "medlang.l"
{ return NOT; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 119 "medlang.l"
{ return PLUS; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 120 "medlang.l"
{ return MINUS; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 121 "medlang.l"
{ return MULTIPLY; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 122 "medlang.l"
{ return DIVIDE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 123 "medlang.l"
{ return MOD; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 125 "medlang.l"
{ return SEMICOLON; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 126 "medlang.l"
{ return LPAREN; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 127 "medlang.l"
{ return RPAREN; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 128 "medlang.l"
{ return LBRACE; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 129 "medlang.l"
{ return RBRACE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 130 "medlang.l"
{ return RANGE_OP; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 131 "medlang.l"
{ return COMMA; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 133 "medlang.l"
{
                        yylval.fval = atof(yytext);
                        return FLOAT_LITERAL;
                    }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 138 "medlang.l"
{
                        yylval.ival = atoi(yytext);
                        return INT_LITERAL;
                    }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 143 "medlang.l"
{
                        yylval.sval = strdup(yytext + 1);
                        yylval.sval[yyleng - 2] = '\0';
                        return STRING_LITERAL;
                    }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 149 "medlang.l"
{
                        fprintf(stderr,
                            "[MedLang Error] Line %d: unterminated string literal\n", lineno);
                        lineno++;
                    }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 155 "medlang.l"
{
                        yylval.ival = yytext[1];
                        return INT_LITERAL;
                    }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 160 "medlang.l"
{
                        yylval.sval = strdup(yytext);
                        return IDENTIFIER;
                    }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 165 "medlang.l"
{ lineno++; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 166 "medlang.l"
{ /* skip spaces and tabs */ }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 168 "medlang.l"
{
                        fprintf(stderr,
                            "[MedLang Error] Line %d: unknown character '%s'\n",
                            lineno, yytext);
                    }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 174 "medlang.l"
ECHO;
	YY_BREAK
#line 1336 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 448 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 448 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 447);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 174 "medlang.l"
